language: python

dist: xenial

python:
  - "3.8"

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install pipenv
  - pipenv install --dev --pre

before_script:
  - pipenv run pyflakes .
  - pipenv run black check .

script:
  - pipenv run pytest
